version: "3.8"

services:
  couchbase:
    image: couchbase:community-7.2.4
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password@123
    volumes:
      - couchbase_data:/opt/couchbase/var
    restart: unless-stopped

volumes:
  couchbase_data:
